name: Reusable Starter

on:
  workflow_call:
    inputs:
      buildCommand:
        description: ビルドコマンド
        type: string
        required: false
        default: ./build.sh
      buildArtifacts:
        description: ビルド成果物
        type: string
        required: false
        default: '**/*.jar'
      staticAnalysisCommand:
        description: 静的解析コマンド
        type: string
        required: false
        default: ./static-analysis.sh
      staticAnalysisReports:
        description: 静的解析レポート
        type: string
        required: false
        default: '**/spotbugsXml.xml'
      unitTestCommand:
        description: 単体テストコマンド
        type: string
        required: false
        default: './unit-test.sh'
      unitTestReports:
        description: 単体テストレポート
        type: string
        required: false
        default: '**/TEST-*.xml'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4.2.2
    - name: Set up JDK 17
      uses: actions/setup-java@v4.7.0
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: ${{ inputs.buildCommand }}
    - name: Upload Build Artifacts
      if: success()
      uses: actions/upload-artifact@v4.6.0
      with:
        name: build-artifacts
        path: ${{ inputs.buildArtifacts }}
    # - name: Send Teams Message
    #   if: always()
    #   uses: tlolkema/simple-teams-message@1.1.0
    #   with:
    #     message_title: "title"
    #     message_description: "description"
    #     webhook: ${{ secrets.TEAMS_WEBHOOK }}

  static-analysis:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      checks: write
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4.2.2
    - name: Set up JDK 17
      uses: actions/setup-java@v4.7.0
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Static Analysis with SpotBugs
      run: ${{ inputs.staticAnalysisCommand }}
    - name: Publish Test Reports
      if: always()
      uses: jwgmeligmeyling/spotbugs-github-action@v1.2
      with:
        path: ${{ inputs.staticAnalysisReports }}
    - name: Upload Static Analysis Reports
      if: always()
      uses: actions/upload-artifact@v4.6.0
      with:
        name: sa-reports
        path: ${{ inputs.staticAnalysisReports }}

  unit-test:
    needs: static-analysis
    runs-on: ubuntu-latest
    permissions:
      checks: write
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4.2.2
    - name: Set up JDK 17
      uses: actions/setup-java@v4.7.0
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Unit Test with JUnit
      run: ${{ inputs.unitTestCommand }}
    - name: Publish Test Reports
      if: always()
      uses: mikepenz/action-junit-report@v5.2.0
      with:
        report_paths: ${{ inputs.unitTestReports }}
    - name: Upload Unit Test Reports
      if: always()
      uses: actions/upload-artifact@v4.6.0
      with:
        name: ut-reports
        path: ${{ inputs.unitTestReports }}
